#' Filter players based on Glicko rating.
#' 
#' This function accepts a set of ANR OCTGN data with accompanying Glicko player
#' ratings generated by rate.players and filters players out based on a minimum
#' rating, maximum deviation, and minimum number of games played. 
#' 
#' @param player.ratings A data frame produced by rate.players().
#' @param min.rating The minimum Glicko rating a player must have to be
#'   included, by default 1500.
#' @param max.deviation The maximum Glicko deviation a player can have to be
#'   included, by default 150.
#' @param min.games The minimum number of games a player must have played to be
#'   included, by default 5.
#' @return A data frame of computed ratings limited to players
#'   rated above \code{min.rating}.
#' @import dplyr
#'   
#' @export

prune.players <- function( player.ratings, min.rating = 1500, max.deviation = 150, min.games = 5 ) {
  
  # Prune to > 5 games played. 
  # This actually eliminates about 50% of the remaining players, so it's pretty common for OCTGN
  # players to try it a few times and then quit. 
  player.ratings <-  filter(player.ratings, Rating >= min.rating,
                                            Deviation <= max.deviation,
                                            Games >= min.games)
  
  return(player.ratings)
  
}